#include <iostream>
#include <vector>
#include <cstring>

class Complex {
    double re = 0.0; 
    double im = 0.0;

public:

    //bad code practise - firsly field is initialized with 0 and then assigned with real
    //it's not critical for primitives but for object we will create object with default construcotr firsly and the assign new object using assinment operator 
    #if 0
    Complex(double real) {
        this->re = re; 
    }
    #endif

    //value 0.0 is ignored
    Complex(double re): re(re) /* member initializer list, works before constructor, order the same as for members*/{}
    Complex(double re, double im): re(re), im(im){}
    //also because constructor is a method we can define it outside class body 
    Complex();
};
Complex::Complex() {
    std::cout << "Default constructor\n";
}

//=================================================================================
//Practical example
class String {
    char* arr = nullptr; 
    size_t sz = 0; 
    size_t cap = 0; 

    //delegating cosntructor C++11
    //when can put only one constructor in member initialization list 
    String(size_t n): arr(new char[n + 1]), sz(n), cap(n + 1){
        arr[sz] = '\0';
    }
public:
    String() = default; //default constructor. Also we can write String() = delete to block this constructor / method 
    String(size_t n, char c): String(n) {
        memset(arr, c, sz); //std::fill(arr, arr + sz, c) - almost the same 
        //memswet and std::fill make only1 operation by 1 machine word (for example 8 bytes), in for-loop we will make operation per byte 
        std::cout << "String(sz, ch)\n";
    }

    //constructor from initializer list (after C++ 11)
    //how it is implemented? is it hardcoded by compiler? 
    String(std::initializer_list<char> list): String(list.size()) {
        std::copy(list.begin(), list.end(), arr);
        std::cout << "String(init_list)\n";
    }

    //copy constructor 
    //this constructor is generated by default and for dynamicly allocated objects could provide to double free 
    //default copy constructor just simply copy members of the class 

    //Copy on write - lazy copy only when needed
    String(const String& other): String(other.sz) {
        memcpy(arr, other.arr, sz); //copy by machine words. but for object std::copy needed - constructors called 
        //memmove correctly worked even if memory areas are overlaped
    }

    //destructor
    ~String(){
        delete[] arr; 
    }
};

//=================================================================================
//Sometimes it's impossible to create instance of the class using default constructor 
struct C { 
    int& r; //in memory reference look like pointer. for example class with one reference member has size of one pointer
    const int c;
    //reference and consts can't be uninitialized
};

//=================================================================================
int glob = 0; 
struct B {
    int& x = glob;

    B(int y) {
        x = y; //x == glob, so now glob == y and everything ok 
    }
    #if 0
    B(int y): x(y) {} //binding reference because we are trying to initialize reference with local variable 
    #endif
};

//=================================================================================
//This example is UB. Why? Using flag -WExtra we can catch this problem. 
//expanding of lifetime for rvalue works only inside functions but doesnt work inside class. Thats why UB 
struct G {
    const int& x; 
    G(int y): x(y){}
};

int main() {
    Complex cmx(5.0); //direct initialization 
    Complex cmx2 = 6.0; //value initialization
    Complex cmx3{7.0};
    Complex cmx4 = {8.0}; 

    std::vector<int> k = {1, 2, 3, 4, 5}; //how does it work? -> constructor from std::initializer_list 

    //=================================================================================
    String v; //default initialization

    //what the problem with initializer lists? sometimes it's really hard to understand which constructor really was called 
    String v1{'a', 'b', 'c'}; //String(init_list)
    String v2{2, 'a'}; //String(init_list)
    String v3{'a', 2}; //String(init_list)
    String v4(2, 'a'); //String(sz, ch)
    //Rule is following: if we have at least one constructor from initializer 
    //list and we use {} - firsly all matching constructr with init_list called
    //but if no constructors available and we use {} and fields are public - aggregation initialization
    String s5 = s5; //UB

    v4.~String(); //UB -> double free after leaving scope
    //order: fields constructors, class constructor, class destructor, fields destructors 
}